mysql_repo_url: "http://dev.mysql.com/get/mysql-community-release-el{{ ansible_distribution_major_version }}-5.noarch.rpm"
mysql_secret_file: /root/.mysql_secret
mysql_root_password: alamakota

mysql_port: 3306
mysql_server_id: 1
mysql_datadir: /var/lib/mysql/
mysql_log_directory: /var/log/mysql

mysql_databases:
  - example_com


mysql_users:
 - { name: "example_com", password: "alamakota", host: "localhost", privileges: "example_com.*:ALL" }