 - name: place ssh configuration file in place
   template:
     src: sshd_config.j2
     dest: /etc/ssh/sshd_config
     owner: root
     group: root
     mode: 0755
   notify: restart ssh
   tags:
     - ssh


 - name: ensure the ssh is up and running
   service:
     name: sshd
     state: started
     enabled: yes
   tags:
     - ssh