 - name: create mysql log directory exists
   file:
     path: "{{ mysql_log_directory }}"
     state: directory
     mode: 0775
     owner: root
     group: toor
   tags:
     - mysql
     - configure


 - name: set my.cnf file
   template:
     src: my.cnf.j2
     dest: /etc/my.cnf
     owner: root
     group: root
     mode: 0644
   notify: restart mysql
   tags:
     - mysql
     - configure


 - name: set ~/.my.cnf file
   template:
     src: dot_my.cnf.j2
     dest: ~/.my.cnf
     owner: vagrant
     group: vagrant
     mode: 0600
   notify:
     - restart mysql
