 # Install MySQL server
 - include: install.yml

 # Configure MySQL
 - include: configure.yml

 # Simulate MySQL secure installation
 - include: mysql_secure_installation.yml

 # Setup users and databases
 - include: users_and_databases.yml

 - name: ensure mysql is up and running
   service:
     name: mysqld
     state: started
     enabled: yes
   tags:
     - mysql