 - name: start mysql service
   service:
     name: mysqld
     state: started
   tags:
    - mysql
    - mysql_secure_installation


 - name: cerate new password for root user
   command: {{ item }}
   with_items:
    - "mysqladmin -u root password {{ mysql_root_password }}"
    - "touch "{{ mysql_data_directory }}/.mysql-root-password-has-been-set-by-ansible"
   args:
     creates: "{{ mysql_data_directory }}/.mysql-root-password-has-been-set-by-ansible"
   tags:
    - mysql
    - mysql_secure_installation


 - name: set ~/.my.cnf file for root account
   template:
     src: .my.cnf.j2
     dest: ~/.my.cnf
     mode: 0600
     owner: root
     group: root
   tags:
    - mysql
    - mysql_secure_installation


 - name: set ~/.my.cnf file for developer account
   template:
     src: .my.cnf.j2
     dest: "/home/{{ developer_user }}/.my.cnf"
     mode: 0600
     owner: "{{ developer_user }}"
     group: "{{ developer_user }}"
   tags:
    - mysql
    - mysql_secure_installation


 - name: remove anonymous users
   mysql_user:
     name: ""
     host: "{{ item }}"
     state: absent
   with_items:
    - localhost
    - "{{ ansible_hostname }}"
   tags:
    - mysql
    - mysql_secure_installation


 - name: remove the test database
   mysql_db:
     name: test
     state: absent
   tags:
    - mysql
    - mysql_secure_installation