 - name: create apache group
   group:
     name: "{{ httpd_group }}"
     state: present
   tags:
     - httpd
     - configure


 - name: create apache user
   user:
     name: "{{ httpd_user }}"
     group: "{{ httpd_group }}"
     createhome: no
     state: present
   tags:
     - httpd
     - configure


 - name: change ownership of apache installation
   file:
     path: "{{ httpd_installation_path }}"
     owner: "{{ httpd_user }}"
     group: "{{ httpd_group }}"
     recurse: yes
   tags:
     - httpd
     - configure


 - name: set httpd.conf file
   template:
     src: httpd.conf.j2
     dest: "{{ httpd_installation_path }}/conf/httpd.conf"
     owner: "{{ httpd_user }}"
     group: "{{ httpd_group }}"
     mode: 0644
   notify: restart httpd
   tags:
     - httpd
     - configure


 - name: set httpd-mpm.conf file
   template:
     src: httpd-mpm.conf.j2
     dest: "{{ httpd_installation_path }}/conf/extra/httpd-mpm.conf"
     owner: "{{ httpd_user }}"
     group: "{{ httpd_group }}"
     mode: 0644
   notify: restart httpd
   tags:
     - httpd
     - configure


 - name: set httpd-security.conf file
   template:
     src: httpd-security.conf.j2
     dest: "{{ httpd_installation_path }}/conf/extra/httpd-security.conf"
     owner: "{{ httpd_user }}"
     group: "{{ httpd_group }}"
     mode: 0644
   notify: restart httpd
   tags:
     - httpd
     - configure
