 - name: update everything
   yum:
     name: "*"
     state: latest
   tags:
     - common


 - name: install ansible packages
   yum:
     name: "{{ item }}"
     state: present
   with_items:
     - libselinux-python
     - MySQL-python
   tags:
     - common

 - name: install useful system tools
   yum:
     name: "{{ item }}"
     state: present
   with_items:
     - yum-utils
     - wget
   tags:
     - common


 - name: make sure that build group exists
   group:
     name: "{{ build_user_group }}"
     state: present
   tags:
     - common


 - name: make sure that build user exists
   user:
     name: "{{ build_user }}"
     group: "{{ build_user_group }}"
     state: present
   tags:
     - common


 - name: make sure that build directory exists
   file:
     path: "{{ build_directory }}"
     state: directory
     mode: 0755
     owner: "{{ build_user }}"
     group: "{{ build_user_group }}"
   tags:
     - common


 - name: make sure that www group exists
   group:
     name: "{{ www_group }}"
     state: present
   tags:
     - common