 # Build PHP
 - include: build.yml

 # /etc/init.d script and alter PATH
 - include: scripts.yml

 # Configure PHP
 - include: configure.yml


 - name: ensure php-fpm is up and running
   service:
     name: php-fpm
     state: started
     enabled: yes
   tags:
     - php