 - name: add script to /etc/init.d
   template:
     src: service-php-fpm.j2
     dest: /etc/init.d/php-fpm
     owner: root
     group: root
     mode: 0755
   tags:
     - php
     - scripts


 - name: add script to /etc/profile.d
   template:
     src: profile-php.sh.j2
     dest: /etc/profile.d/php.sh
     owner: root
     group: root
     mode: 0755
   tags:
     - php
     - scripts